// <auto-generated />
using System;
using Greenhouse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Greenhouse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GreenhouseDbContext))]
    partial class GreenhouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Greenhouse.Domain.Nawy.Nawa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MoistureMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MoistureMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantNote")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TemperatureMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TemperatureMin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Nawy", (string)null);
                });

            modelBuilder.Entity("Greenhouse.Domain.SensorReadings.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Battery")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CleaningReminder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("IlluminanceAverage20MinRaw")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IlluminanceMaximumTodayRaw")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IlluminanceRaw")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkQuality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Rain")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RainIntensityRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorIdentifier")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoilMoisture")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SensorIdentifier");

                    b.HasIndex("SensorId", "ReceivedAtUtc");

                    b.HasIndex("SensorId", "PayloadHash", "ReceivedAtUtc");

                    b.ToTable("SensorReadings", (string)null);
                });

            modelBuilder.Entity("Greenhouse.Domain.Sensors.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NawaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NawaId");

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("Greenhouse.Domain.SensorReadings.SensorReading", b =>
                {
                    b.HasOne("Greenhouse.Domain.Sensors.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Greenhouse.Domain.Sensors.Sensor", b =>
                {
                    b.HasOne("Greenhouse.Domain.Nawy.Nawa", null)
                        .WithMany()
                        .HasForeignKey("NawaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
